name: Deploy da Aplicação

# Controla quando a ação será executada
on:
  # Dispara o workflow em eventos de push para a branch main
  push:
    branches: [ "main" ]
  # Permite executar este workflow manualmente através da interface do GitHub
  workflow_dispatch:

jobs:
  # Job de deploy
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Faz o deploy via SSH usando senha
      - name: Deploy para o servidor
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 191.252.177.174
          username: root
          password: "MZE36vkT@#"
          script: |
            cd /var/www/timeboard/votacao
            git pull origin main
            yarn
            yarn build
            pm2 restart votacao || pm2 start yarn --name "votacao" -- start 